name: run-bot

on: workflow_dispatch

jobs:
  jcefmavenbot:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Run jcefmavenbot build issuer module
        run: |
          chmod +x run.sh
          ./run.sh BOTH ${{ secrets.DOCKERHUB_REPOSITORY }} ${{ secrets.JCEFMAVEN_BOT_PAT }}